BasaDate/BasaDate/Models/visitor.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasaDate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class visitor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public visitor()
        {
            this.sessions = new HashSet<session>();
        }
    
        public int id { get; set; }
        public string full_name { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public long phone_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<session> sessions { get; set; }
    }
}

BasaDate/BasaDate/Controllers/visitorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BasaDate.Models;

namespace BasaDate.Controllers
{
    public class visitorsController : Controller
    {
        private Model1Container db = new Model1Container();

        // GET: visitors
        public ActionResult Index()
        {
            return View(db.visitors.ToList());
        }

        // GET: visitors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            visitor visitor = db.visitors.Find(id);
            if (visitor == null)
            {
                return HttpNotFound();
            }
            return View(visitor);
        }

        // GET: visitors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: visitors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,full_name,date_of_birth,phone_number")] visitor visitor)
        {
            if (ModelState.IsValid)
            {
                db.visitors.Add(visitor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(visitor);
        }

        // GET: visitors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            visitor visitor = db.visitors.Find(id);
            if (visitor == null)
            {
                return HttpNotFound();
            }
            return View(visitor);
        }

        // POST: visitors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,full_name,date_of_birth,phone_number")] visitor visitor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(visitor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(visitor);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(string search)
        {

            var result = db.visitors
               .Where(a => a.full_name.ToLower().Contains(search.ToLower()))
               .ToList();
            return View(result);
        }


        // GET: visitors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            visitor visitor = db.visitors.Find(id);
            if (visitor == null)
            {
                return HttpNotFound();
            }
            return View(visitor);
        }

        // POST: visitors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            visitor visitor = db.visitors.Find(id);
            db.visitors.Remove(visitor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BasaDate/BasaDate/Views/visitors/Create.cshtml
@model BasaDate.Models.visitor

@{
    ViewBag.Title = "Добавление";
}

<h2>Добавление</h2>
<style>
    .lol {
        margin-left: 17%;
    }
</style>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Посетители</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.full_name, "Полное имя", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.full_name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.full_name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="lol">
        <p><i>Формат даты: ГГГГ-ММ-ДД</i></p>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.date_of_birth, "Дата рождения", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.date_of_birth, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.date_of_birth, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.phone_number, "Номер телефона", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.phone_number, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.phone_number, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Добавить" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Назад","Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BasaDate/BasaDate/Views/visitors/Delete.cshtml
@model BasaDate.Models.visitor

@{
    ViewBag.Title = "Удаление";
}

<h2>Удаление</h2>

<h3>Вы уверены, что хотите удалить?</h3>
<div>
    <h4>Посетители</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <p>Полное имя</p>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.full_name)
        </dd>

        <dt>
            <p>Дата рождения</p>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date_of_birth)
        </dd>

        <dt>
            <p>Номер телефона</p>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone_number)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Назад", "Index")
        </div>
    }
</div>

BasaDate/BasaDate/Views/visitors/Details.cshtml
@model BasaDate.Models.visitor

@{
    ViewBag.Title = "Подробнее";
}

    <h2>Подробнее</h2>

<div>
    <h4>Посетители</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <p>Полное имя</p>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.full_name)
        </dd>

        <dt>
            <p>Дата рождения</p>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date_of_birth)
        </dd>

        <dt>
            <p>Номер телефона</p>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone_number)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Изменение", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Назад", "Index")
</p>

BasaDate/BasaDate/Views/visitors/Edit.cshtml
@model BasaDate.Models.visitor

@{
    ViewBag.Title = "Изменение";
}

<h2>Изменение</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Посетители</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.full_name,"Полное  имя", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.full_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.full_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date_of_birth,"Дата рождения", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date_of_birth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date_of_birth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone_number,"Номер телефона", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone_number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone_number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BasaDate/BasaDate/Views/visitors/Index.cshtml
@model IEnumerable<BasaDate.Models.visitor>

@{
    ViewBag.Title = "Посетители";
}

<h2>Посетители</h2>

<p>
    @Html.ActionLink("Добавить запись", "Create")
</p>
<table class="table">
    <tr>
        <th>
            <p>Полное имя</p>
        </th>
        <th>
            <p>Дата рождения</p>
        </th>
        <th>
            <p>Номер телефона</p>
        </th>
        <th></th>
    </tr>

    @using (Html.BeginForm("Index", "visitors", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <div class="col-md-10">
                <label for="query">
                    <input type="text" name="search" class="form-control" />
                </label>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Поиск" class="btn btn-default" />
            </div>
        </div>
    }

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.full_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.date_of_birth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.phone_number)
            </td>
            <td>
                @Html.ActionLink("Изменение", "Edit", new { id = item.id }) |
                @Html.ActionLink("Подробнее", "Details", new { id = item.id }) |
                @Html.ActionLink("Удаление", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>