BasaDate/BasaDate/Controllers/adminsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BasaDate.Models;
using Npgsql;

namespace BasaDate.Controllers
{
    public class adminsController : Controller
    {
        private Model1Container db = new Model1Container();

        // GET: admins
        
        public ActionResult Index()
        {
            return View(db.admins.ToList());
        }

        // GET: admins/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            admin admin = db.admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }

        // GET: admins/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: admins/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Create([Bind(Include = "id,full_name")] admin admin)
        {
            if (ModelState.IsValid)
            {
                db.admins.Add(admin);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(admin);
        }

        // GET: admins/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            admin admin = db.admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }

        // POST: admins/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Edit([Bind(Include = "id,full_name")] admin admin)
        {
            if (ModelState.IsValid)
            {
                db.Entry(admin).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(admin);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(string search)
        {
    
            var result = db.admins
               .Where(a => a.full_name.ToLower().Contains(search.ToLower()))
               .ToList();
            return View(result);
        }


        // GET: admins/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            admin admin = db.admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }

        // POST: admins/Delete/5
        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            admin admin = db.admins.Find(id);
            db.admins.Remove(admin);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BasaDate/BasaDate/Views/admins/Create.cshtml
@model BasaDate.Models.admin

@{
    ViewBag.Title = "Добавление";
}

<h2>Добавление</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Администраторы</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.full_name, "Администратор", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.full_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.full_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BasaDate/BasaDate/Views/admins/Delete.cshtml
@model BasaDate.Models.admin

@{
    ViewBag.Title = "Удаление";
}

<h2>Удаление</h2>

<h3>Вы уверены, что хотите удалить?</h3>
<div>
    <h4>Администраторы</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <p>Администратор</p>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.full_name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Назад", "Index")
        </div>
    }
</div>

BasaDate/BasaDate/Views/admins/Details.cshtml
@model BasaDate.Models.admin

@{
    ViewBag.Title = "Подробнее";
}

<h2>Подробнее</h2>

<div>
    <h4>Администраторы</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <p>Администратор</p>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.full_name)
        </dd>

    </dl>
</div>
<p>
    @if (User.IsInRole("admin")) {@Html.ActionLink("Изменение", "Edit", new { id = Model.id })} |
    @Html.ActionLink("Назад", "Index")
</p>

BasaDate/BasaDate/Views/admins/Edit.cshtml
@model BasaDate.Models.admin

@{
    ViewBag.Title = "Изменение";
}

<h2>Изменение</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Администарторы</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.full_name,"Администратор", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.full_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.full_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BasaDate/BasaDate/Views/admins/Index.cshtml
@model IEnumerable<BasaDate.Models.admin>

@{
    ViewBag.Title = "Адмнистраторы";
}

<h2>Администраторы</h2>

<p>
   @if (User.IsInRole("admin")) { @Html.ActionLink("Добавить запись", "Create")}
</p>
<table class="table">
    <tr>
        <th>
            <p>Администраторы</p>
        </th>
        <th></th>
    </tr>

     @using (Html.BeginForm("Index", "admins", FormMethod.Post))
    {
    @Html.AntiForgeryToken()
    <div class="form-group">
        <div class="col-md-10">
            <label for="query">
                <input type="text" name="search" class="form-control" />
            </label>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Поиск" class="btn btn-default" />
        </div>
    </div>
    }

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.full_name)
        </td>
        <td>
            @if (User.IsInRole("admin")) {@Html.ActionLink("Изменение", "Edit", new { id = item.id })} |
            @Html.ActionLink("Подробнее", "Details", new { id=item.id }) |
            @if (User.IsInRole("admin")) {@Html.ActionLink("Удаление", "Delete", new { id = item.id })}
        </td>
    </tr>
}

</table>