BasaDate/BasaDate/Models/software.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasaDate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class software
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public software()
        {
            this.personal_computer = new HashSet<personal_computer>();
        }
    
        public int id { get; set; }
        public string os { get; set; }
        public string programs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personal_computer> personal_computer { get; set; }
    }
}

BasaDate/BasaDate/Controllers/softwaresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BasaDate.Models;

namespace BasaDate.Controllers
{
    public class softwaresController : Controller
    {
        private Model1Container db = new Model1Container();

        // GET: softwares
        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            return View(db.softwares.ToList());
        }

        // GET: softwares/Details/5
        [Authorize(Roles = "admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            software software = db.softwares.Find(id);
            if (software == null)
            {
                return HttpNotFound();
            }
            return View(software);
        }

        // GET: softwares/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: softwares/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Create([Bind(Include = "id,os,programs")] software software)
        {
            if (ModelState.IsValid)
            {
                db.softwares.Add(software);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(software);
        }

        // GET: softwares/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            software software = db.softwares.Find(id);
            if (software == null)
            {
                return HttpNotFound();
            }
            return View(software);
        }

        // POST: softwares/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Edit([Bind(Include = "id,os,programs")] software software)
        {
            if (ModelState.IsValid)
            {
                db.Entry(software).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(software);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Index(string search)
        {

            var result = db.softwares
               .Where(a => a.os.ToLower().Contains(search.ToLower()))
              
               .ToList();
            return View(result);
        }

        // GET: softwares/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            software software = db.softwares.Find(id);
            if (software == null)
            {
                return HttpNotFound();
            }
            return View(software);
        }

        // POST: softwares/Delete/5
        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            software software = db.softwares.Find(id);
            db.softwares.Remove(software);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BasaDate/BasaDate/Views/softwares/Create.cshtml
@model BasaDate.Models.software

@{
    ViewBag.Title = "Добавление";
}

<h2>Добавление</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ПО</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.os, "Операционная система", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.os, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.os, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.programs,"Программы", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.programs, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.programs, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BasaDate/BasaDate/Views/softwares/Delete.cshtml
@model BasaDate.Models.software

@{
    ViewBag.Title = "Удаление";
}

<h2>Удаление</h2>

<h3>Вы уверены, что хотите удалить?</h3>
<div>
    <h4>ПО</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <p>Операционная система</p>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.os)
        </dd>

        <dt>
            <p>Программы</p>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.programs)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Назад", "Index")
        </div>
    }
</div>

BasaDate/BasaDate/Views/softwares/Details.cshtml
@model BasaDate.Models.software

@{
    ViewBag.Title = "Подробнее";
}

<h2>Подробнее</h2>

<div>
    <h4>ПО</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <p>Операционная система</p>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.os)
        </dd>

        <dt>
            <p>Программы</p>
       </dt>

        <dd>
            @Html.DisplayFor(model => model.programs)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Изменение", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Назад", "Index")
</p>

BasaDate/BasaDate/Views/softwares/Edit.cshtml
@model BasaDate.Models.software

@{
    ViewBag.Title = "Изменение";
}

<h2>Изменение</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ПО</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.os, "Операционная система", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.os, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.os, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.programs, "Программы", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.programs, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.programs, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BasaDate/BasaDate/Views/softwares/Index.cshtml
@model IEnumerable<BasaDate.Models.software>

@{
    ViewBag.Title = "ПО";
}

<h2>ПО</h2>

<p>
    @Html.ActionLink("Добавить записи", "Create")
</p>
<table class="table">
    <tr>
        <th>
            <p>Операционная система</p>
        </th>
        <th>
            <p>Программы</p>
        </th>
        <th></th>
    </tr>

    @using (Html.BeginForm("Index", "softwares", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <div class="col-md-10">
                <label for="query">
                    <input type="text" name="search" class="form-control" />
                </label>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Поиск" class="btn btn-default" />
            </div>
        </div>
    }

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.os)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.programs)
            </td>
            <td>
                @Html.ActionLink("Изменить", "Edit", new { id = item.id }) |
                @Html.ActionLink("Подробнее", "Details", new { id = item.id }) |
                @Html.ActionLink("Удаление", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>